- package.json
- src/Tracker.js
- src/components/App.js
- src/index.js
- webpack.config.js
- yarn.lock
@Wikia/cake 
Tracks user actions when using the modal. Whether or not including the beacon is considered personably identifiable information is TBD. If it is the tracking implementation might change, but its usage and interface should remain the same.
> Cake 3141 - track user actions 

- package.json
- release/jenkins
- release/scripts/validate-jenkins-files.sh
After taking a closer look at the jenkins UI (it's a maze) I noticed there were additional options that could be provided to the initial SCM checkout. In those options you can specify that you want the repo to be cleaned before and after the checkout. That should ensure a pristine repo so we can remove the redundant internal checkout.
I must have been so excited to get the deploy working in the FC that I overlooked this option. If it works as expected here we can update that workflow as well.
As part of this, I also added tooling to validate the jenkins file. Having to commit, push, go to jenkins, rebuild, repeat slows down the iteration on building the release pipeline. This should help improve that process by giving the developer a local means for validating the file without having to …
> Remove the manual checkout from the jenkins pipeline script

- demo.html
- src/components/App.js
- src/components/styles.scss
- src/index.js
@Wikia/cake 
Prevents scrolling while the opt-in dialog is shown. According to caniuse.com both [`querySelector`](https://caniuse.com/#search=queryselector) and [`classList`](https://caniuse.com/#search=classlist) work on our [supported browsers](http://community.wikia.com/wiki/Help%3ASupported_browsers).
> param to prevent scroll while the dialog is shown

- src/ContentManager.js
- src/LangManager-test.js
Chrome uses the following language tags for Chinese:
- Chinese: `zh`
- Chinese (Simplified): `zh-CN`
- Chinese (Hong Kong): `zh-HK`
- Chinese (Traditional): `zh-TW`
Changed simplified from `zh-hans` to `zh`. This should be a reasonable default since there are more simplified readers than traditional. The language lookup logic falls back to the first 2 characters so `zh-CN` will correctly land on `zh`.
Changed traditional from `zh-hant` to `zh-TW` and copied `zh-TW` to `zh-HK`. Traditional is used in Hong Kong so this is a more appropriate setting for those users.
@Wikia/cake
> CAKE-3194 Change simplified to zh and  add zh-TW and zh-HK using traditional

- src/TrackingOptIn-test.js
- src/TrackingOptIn.js
- src/index.js
- src/urlUtils.js
Whitelists the `privacyLink` and `partnerLink` from the content manager. Not sure how to write a selenium test for this until it's actually live on those pages. 
@Wikia/cake
> CAKE-3172 | Whitelist prod privacy and partner pages

- README.md
- src/OptInManager-test.js
- src/OptInManager.js
- src/index.js
@Wikia/cake 
Sets an expiration time on the rejection cookie so that users aren't prompted on each browser session.
> rejection expiration time

- src/components/App.js
- src/components/styles.scss
Prevent some scrolling by reducing last paragraph size and increase some specificity. 
The source of these style issues are the very generic selectors on upstream. I'm sure I missed some styles but I'm skeptical of the cost-benefit of the time to track down each little specificity issue on a platform with very low traffic. 
@Wikia/cake
> CAKE-3193 | Design Updates

- src/ContentManager.js
@Wikia/cake 
The changes from #43 mistakenly set the partner list text to be the same as the privacy policy text in Polish.
> fix polish translation

- release/jenkins
The major dependency of this build is nodejs.  Changing nodejs version seems to trigger a g++ build.  g++ is installed on executors, but not docker-builder
so this build might be better suited to qa-executor nodes.
> Run jenkins tasks on qa executors instead

- package.json
- webpack.config.js
Uses host `0.0.0.0` to work on devbox and add `yarn nohup` to make process run in the background
@Wikia/cake
> Ability to serve from devbox

- src/components/PreferencesVendorList.js
This fixes a bug where a vendor shows "allowed" even if it's been disallowed. We need to check both the vendor and purpose to determine if it's allowed.
> CAKE-5003 Fix disallowed indication when vendor is disallowed

- package.json
- webpack.config.js
Webpack doesn't like the `serve` option being used in production mode, but we'd still like to use it for testing. So this reverts https://github.com/Wikia/tracking-opt-in/commit/e4ca1732d298c5e685664da1c77110a882b244fe#diff-11e9f7f953edc64ba14b0cc350ae7b9d while adding an environment var check to toggle serving on port 3000.
> Serve prod alternate method

- src/components/PreferencesVendorList.scss
This was already done for other links but was missed in this file.
> CAKE-5003 Override link color from Fandom Creator communities

- src/components/Preferences.js
The second screen/overlay was missing a HTML attribute which was used for testing. This adds it back.
> CAKE-5093 Add HTML attribute for testing

- README.md
- package.json
- src/TrackingOptIn-test.js
- src/TrackingOptIn.js
- src/components/App.js
In order to accommodate existing logic on platforms using the GDPR dialog, we need to revert to using two separate callbacks from the dialog -- onAcceptTracking and onRejectTracking. These will be called when non-IAB vendor tracking is either accepted or rejected. The user-allowed IAB vendors and purposes will be passed as parameters to either callback as arrays.
Additionally I've fixed a race condition when initializing the CMP by utilizing an existing Promise.
> ADEN-9245 Revert to using two callbacks for accept or reject

- selenium/test.js
- src/GeoManager-test.js
- src/LangManager.js
- src/utils.js
Replaces an object not supported by IE11. The `isParameterSet` function could instead use the same method, but I couldn't get window.location mocking to work that way for the mobile app unit test.
> CAKE-5097 Don't use cutting Edge JS object

- src/components/Preferences.scss
- src/components/ScreenOne.scss
- src/components/styles.scss
Tested in IE 11 on Windows 10, and checked for backward-compatibility in Chromium.
> CAKE-5110 Make styling compatible with IE 11

- src/utils-test.js
- src/utils.js
This fixes an issue where we were attempting to set a cookie on the co.uk SLD rather than the proper full domain (eg. fm-base.co.uk).
> CAKE-5105 Fix cookie domain for .co.uk (and others)

- package.json
- src/components/Preferences.scss
- src/components/ScreenOne.scss
Prevent the bottom buttons from becoming hidden behind the native browser UI.
> CAKE-5106 Fix buttons hidden on mobile screens

- src/gdpr/ConsentManagementProvider.js
- src/gdpr/TrackingOptIn.js
- src/index.js
Move body of gatherTCF2Consent method into a Promise body,
which is resolved once vendor-list.json is fetched.
The vendor-list.json is cached for a week so we're safe
to postpone execution until it's downloaded.
> ADEN-10225 Remove euconsent-v2 cookie if GVL tcfPolicyVersion changes.

- src/gdpr/OptInManager.js
- src/gdpr/OptInStatus.js
- src/gdpr/TrackingOptIn-test.js
- src/gdpr/TrackingOptIn.js
- src/gdpr/TransitionOptInStatusTracker.js
Status is stored in a cookie named "tracking-opt-in-transition-status".
It is a pipe ("|") separated string of 2 elements:
* "accepted"
* "rejected"
* "|" - GDPR does not apply
> ADEN-10252 Store GDPR opt-in/opt-out status.

- package.json
- src/gdpr/ConsentManagementPlatform.js
- webpack.config.js
- yarn.lock
As part of our mobile editor performance investigations, we noticed that the tracking-opt-in library was a rather large asset, impacting mobile editor load times on slower connections. Attempt to reduce the impact by doing a quick optimization pass:
* Don't load preact twice - use the ESM version consistently.
* Minify CSS output using `cssnano`.
This cuts down the bundle size from ~273 kB (~73 kB gzipped) to ~234 kB (~67 kB gzipped).
> CATS-3457 | Reduce the bundle size

- src/modal/ScreenOne.js
- src/modal/styles.scss
In this PR I've changed button order on mobile. To do so I had to slightly modify structure of GDPR modal footer and add a few styles. I decided to refator it into Flexbox as it is the most popular and easiest way to arrange items in containers.
> ADEN-13021 - Changed button order on mobile

- src/shared/consts.js
The CordCutterNews platform is not needed and it should be removed
> ADEN-remove-platform-ccn Remove CordCutterNews from TrustedDomains

- src/gdpr/ConsentManagementProvider.js
In this PR I've added Legitimate Interests filtering. Since TCF 2.2 some Legitimate Interests should be blocked, and TCF strings, containing these interests are being recognized as invalid by Pubmatic. I've modified our logic to get only these interests, that are not blocked.
> TACO-269 - Added blocked purposes filtering
