- package.json
- src/ContentManager.js
- src/components/App.js
- src/components/styles.scss
* Added test npm package
* Designs except background
* ~The svg provided was 165KB so I asked if JJ could go back and come up with something smaller and simpler.~
* JJ is okay with removing it
@Wikia/cake
>  CAKE-3135 | NPM Testing and Designs

- src/components/styles.scss
> Better scrolling on short screens

- release/jenkins
@Wikia/cake 
https://wikia-inc.atlassian.net/browse/CAKE-3157
Opening on behalf of @drsnyder
> Cake 3157 - jenkins build pipeline

- src/components/styles.scss
> Style updates after copy changes

- package.json
- release/demo-container/Dockerfile
- release/demo-container/k8s.hbs
- release/demo-container/nginx.conf
- release/jenkins
- release/scripts/generate-k8s-yaml.js
- src/index.js
- yarn.lock
@Wikia/cake 
https://wikia-inc.atlassian.net/browse/CAKE-3158
Creates a docker image and deploys that image to k8s during the release process, and then deletes those resources from k8s when the process finishes, regardless of whether or not the release completed successfully or not.
> Cake 3158 - start test container with latest build during release process

- README.md
> cake-3160 - Update README.md

- selenium/test.js
- src/ContentManager.js
- src/GeoManager-test.js
- src/GeoManager.js
- src/LangManager-test.js
- src/LangManager.js
- src/Tracker.js
- src/TrackingOptIn-test.js
- src/TrackingOptIn.js
- src/components/App-test.js
- src/components/App.js
- src/index.js
> CAKE-3197 | No modal when no geo cookie

- src/ContentManager.js
> CAKE-3207 | Update translations

- webdriver.conf.js
Increase timeouts to prevent erroring out. 
@Wikia/cake
> Timeout bump

- webdriver.conf.js
Increase the length of an individual test on browser stack before timing out. 
http://webdriver.io/guide/getstarted/configuration.html#waitforTimeout
> Increase timeout for browserstack

- src/components/App.js
- src/components/Switch-test.js
- src/components/Switch.js
- src/components/styles.scss
A minimal preact ios switch (styling borrowed from here and there)
> Build toggle component

- selenium/jenkins
- src/LangManager.js
- Updating jenkins node
- Updated LangManger.js to add param for stakeholder and product review
> Jenkins and lang manager update

- selenium/test.js
- src/TrackingOptIn-test.js
- src/components/App-test.js
- src/components/App.js
- src/components/ScreenOne.js
- src/components/ScreenOne.scss
- src/components/styles.scss
- src/i18n/tracking-opt-in.json
- webdriver.conf.js
This PR includes
- Creation of Screen One component with separate styles
- Updates to GDPR modal styles
- Updates to copy in `tracking-opt-in.js`
- Update tests to reflect new GDPR flow
> Cake-5005-2 | Updates to GDPR Screen One

- src/components/App.js
- src/index.js
Minor PR to use the defaults for the vendors/purposes. 
@Wikia/cake
> CAKE-5009 | Use sane defaults for vendors/purposes

- src/ConsentManagementProvider.js
- src/TrackingOptIn.js
- src/components/App-test.js
- src/components/App.js
- src/components/Preferences.js
- src/components/Preferences.scss
- src/components/PreferencesSection.js
- src/components/PreferencesSection.scss
- src/components/ScreenOne.js
- src/components/ScreenOne.scss
- src/components/consts.scss
- src/components/styles.scss
- src/utils-test.js
- src/utils.js
There are still several TODOs for the UI here.
> Add purposes to preferences screen 

- src/components/App.js
- src/components/Preferences.js
- src/components/PreferencesSection.js
- src/components/PreferencesVendorList.js
Tracking events for new two-screen dialog
> CAKE-5019 Hook up remaining tracking events

- src/components/Preferences.js
- src/components/PreferencesSection.js
- src/components/PreferencesVendorList.js
- src/i18n/tracking-opt-in.json
- src/utils.js
- Translations for Purposes and Features
- helper function the convert form ID to proper translation
@mklucsarits
> CAKE-5023 | Add more translations

- README.md
- package.json
- webpack.config.js
* Add namespaced npm commands (`start:dev` and `start:prod`) 
* Update documentation
* Update webpack config
@Wikia/cake
> :memo: Update docs for selenium testing

- src/ConsentManagementProvider.js
- src/components/Preferences-test.js
- src/components/Preferences.js
- src/components/Preferences.scss
- src/components/PreferencesSection.scss
- src/components/PreferencesVendorList.scss
- src/components/ScreenOne.js
- src/components/ScreenOne.scss
- src/components/styles.scss
- src/i18n/tracking-opt-in.json
- src/utils/getParagraphs.js
* Simplified some markup + CSS
* Implemented changes requested by Design
* Reverted CMP cookie version
> CAKE-5003 Design updates and fixes

- src/index.js
Added several new vendors, added some aliases for existing ones, and removed two which are no longer IAB vendors.
> Update our vendor list

- src/components/Preferences-test.js
- src/components/Preferences.js
- src/components/ScreenOne.js
- src/components/styles.scss
Button styles were being overridden by wiki page styles.
> CAKE-5003 Prevent button styles from being overridden

- src/components/App.js
- src/components/Preferences.js
* Add onRejectNonIab property to the preferences component
* Sorted some props
@Wikia/cake
> :sparkles: Ability to reject non-iab vendors

- package.json
- src/Tracker.js
- src/components/App.js
- src/components/OtherPartners.js
- src/components/Preferences.js
- src/components/Preferences.scss
- src/components/PreferencesSection.js
- src/components/PreferencesVendorList.js
- src/components/ScreenOne.scss
- src/consts.js
- src/i18n/tracking-opt-in.json
- src/index.js
This covers the UI for rejecting tracking for non-IAB vendors.
> CAKE-5064 Allow rejection of non-IAB vendors

- package.json
- src/components/Preferences.scss
- src/components/ScreenOne.scss
- src/components/styles.scss
- src/utils-test.js
- src/utils.js
Fixes:
* https://wikia-inc.atlassian.net/browse/CAKE-5105
* https://wikia-inc.atlassian.net/browse/CAKE-5106
* https://wikia-inc.atlassian.net/browse/CAKE-5110
> 2.0.6 integration branch with 3 fixes

- demo.hbs
- src/TrackingOptIn-test.js
- src/TrackingOptIn.js
- src/components/Preferences.js
- src/components/ScreenOne.js
- src/index.js
- src/utils/getParagraphs.js
> CAKE-5211 | Add isCurse param for privacy policy link

- src/ccpa/initialization-test.js
Add missing stubs which were throwing errors in console when running tests.
> Add missing stubs.

- src/modal/PreferencesSection.scss
- src/modal/PreferencesVendorList.scss
- src/modal/Switch.scss
- src/modal/consts.scss
- src/modal/styles.scss
More details including screenshots and a link to Zeplin: https://wikia-inc.atlassian.net/browse/ADEN-11148
> ADEN-11148 Change colors and styles of the modal components

- src/shared/GeoManager.js
See https://github.com/Wikia/ad-engine/pull/1390 and https://github.com/Wikia/wikia-vcl/pull/3055
> CATS-1302 | Add city and country name to Geo cookie on fetch

- src/gdpr/Tracker.js
- src/modal/Modal.js
https://fandom.atlassian.net/browse/ADEN-11833
> ADEN-11833 Assess the number of users who will be affected by GPC in GDPR geo

- src/shared/CookieManager-test.js
https://fandom.atlassian.net/browse/ADEN-11442
> ADEN-11442 Change wikia_session_id to tracking_session_id

- src/shared/consts.js
[Ticket](https://fandom.atlassian.net/browse/ADEN-12299)
> ADEN-12299 - Add new partners

- demo.hbs
- package.json
- src/index.js
- src/onetrust/index.js
- src/shared/consts.js
[Ticket](https://fandom.atlassian.net/browse/ADEN-12406)
This feature is purely Experimental. We should refactor this later, after we decide what should we do about OneTrust later.
> ADEN-12406 - Added OneTrust support

- src/modal/ScreenOne.js
- src/modal/styles.scss
In this PR I've changed current button order on Tracking Opt In modal. Right now Accept is in the middle, and Reject on the right, and we want them to be placed otherwise - Accept on the right, and Reject in the middle.
> ADEN-13007 - Changed button order

- src/modal/Modal.js
- src/modal/ScreenOne.js
- src/shared/GeoManager.js
https://fandom.atlassian.net/browse/ADEN-13227
Hide Reject All feature behind the flag. Default option which will be released global should be set to false.
> ADEN-13227 Hide Reject All feature behind the flag

- src/ccpa/UserSignalMechanism.js
https://fandom.atlassian.net/browse/ADEN-13102
Prebid version 7+ requires implementation of "Data Deletion Request Handling" in CCPA. In this PR I've added it according to this documentation https://github.com/InteractiveAdvertisingBureau/USPrivacy/blob/master/CCPA/Data%20Deletion%20Request%20Handling.md
> ADEN-13102 Add CCPA Data Deletion Request Handling

- src/ccpa/UserSignalMechanism.js
Reverts Wikia/tracking-opt-in#280
> Revert "ADEN-13102 Add CCPA Data Deletion Request Handling"

- src/shared/consts.js
Reverts Wikia/tracking-opt-in#283
> Revert "ADEN-13082 - Added a new partner"

- src/ccpa/UserSignalMechanism.js
Reverts Wikia/tracking-opt-in#284
> Revert "Revert "ADEN-13102 Add CCPA Data Deletion Request Handling""

- src/shared/consts.js
Reverts Wikia/tracking-opt-in#285
> Revert "Revert "ADEN-13082 - Added a new partner""

- .github/pr-labeler.yml
- .github/workflows/pr-labeler.yml
- .github/workflows/workflow.yml
* http://fandom.atlassian.net/browse/TACO-220
Adds Github Actions with PR Labeler. As a bonus, simple test runner Github Action.
> TACO-220 Add Github Actions with PR Labeler and simple test

- src/gdpr/ConsentManagementProvider.js
Trigger consent modal to check if it helps.
> TACO-223 Ozone sees low consent rate

- src/i18n/de/tracking-opt-in.json
- src/i18n/es-ES/tracking-opt-in.json
- src/i18n/fr/tracking-opt-in.json
- src/i18n/it/tracking-opt-in.json
- src/i18n/ja/tracking-opt-in.json
- src/i18n/pl/tracking-opt-in.json
- src/i18n/zh-CN/tracking-opt-in.json
- src/i18n/zh-TW/tracking-opt-in.json
- src/modal/VendorDetails.js
Added missing translations to newly created functionalities in GDPR Modal.
> TACO-231 - Added translations

- src/gdpr/ConsentManagementProvider.js
https://fandom.atlassian.net/browse/TACO-325
In this PR I've added missing Publisher Legitimate Interests (2, 7 , 8, 9, 10, 11) to the TCF string composed by Tracking Opt In.
> TACO-325 Add AllowedPublisherLegitimateInterest to TCF string

- src/shared/consts.js
> TACO-209 Add Yahoo to vendor list

- src/shared/consts.js
Added 2 new partners:
- TrustedStack
- TypeA
> TACO-442 - Added Trusted Stack and TypeA

- src/shared/consts.js
https://fandom.atlassian.net/browse/TACO-444
> TACO-444 Add Next Millenium to vendor list

- compass.yaml
- jobs/Jenkinsfile-deploy
- jobs/Jenkinsfile-deploy-branch
- jobs/functions.groovy
https://fandom.atlassian.net/browse/PLATFORM-9352
> PLATFORM-9352 create Jenkinsfiles for deploy jobs

- jobs/Jenkinsfile-deploy
- jobs/Jenkinsfile-deploy-branch
- jobs/functions.groovy
* http://wikia-inc.atlassian.net/browse/PLATFORM-9370
> PLATFORM-9370 send author and list of related issues to change-tracking
